### ISSUE TITLE
problem with Fastx

### ISSUE THREAD

**Issue by sheucke** [nanoporetech/duplex-tools#31]
I did the following:

----------------------------------------
### create

```bash
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
/bin/bash Miniconda3-latest-Linux-x86_64.sh
source ~/.bashrc
```

```bash
conda create --name nanopore
conda activate nanopore
```

#### duplex-tools

<https://github.com/nanoporetech/duplex-tools>

```bash
conda install -c bioconda duplex-tools
````
--------------------------------------

if I now want to test the installation it gives the following error:

(nanopore) sheucke@PTH2D537:~/nanopore/nanopore$ duplex_tools --help
Traceback (most recent call last):
  File "/home/sheucke/miniconda3/envs/nanopore/bin/duplex_tools", line 6, in <module>
    from duplex_tools import main
  File "/home/sheucke/miniconda3/envs/nanopore/lib/python3.6/site-packages/duplex_tools/__init__.py", line 5, in <module>
    from duplex_tools import \
  File "/home/sheucke/miniconda3/envs/nanopore/lib/python3.6/site-packages/duplex_tools/split_on_adapter.py", line 14, in <module>
    from pyfastx import Fastx
ImportError: cannot import name 'Fastx'

(nanopore) sheucke@PTH2D537:~/nanopore/nanopore$

**Comment by sheucke** [comment]
I also tried with the venv approach, but got the following error:

(base) sheucke@PTH2D537:~/nanopore/tests$ . venv/bin/activate
(duplex) (base) sheucke@PTH2D537:~/nanopore/tests$ pip install duplex_tools
Collecting duplex_tools
  Downloading https://files.pythonhosted.org/packages/18/d4/d1290091cb3f5d3541edc98456749b3a2aba24327768a1cb95757df10b5c/duplex_tools-0.2.20.tar.gz
Collecting edlib (from duplex_tools)
  Downloading https://files.pythonhosted.org/packages/08/a3/37558fb19e54e40e360c8f3e255007d19f262c45298bf3148b92faf3311c/edlib-1.3.9-cp36-cp36m-manylinux1_x86_64.whl (304kB)
    100% |████████████████████████████████| 307kB 21.1MB/s 
Collecting mappy (from duplex_tools)
  Downloading https://files.pythonhosted.org/packages/9b/41/52391258e16bcc8182ddf3133d86408ed17d8d8fd6e30eea4960df29b64b/mappy-2.24.tar.gz (140kB)
    100% |████████████████████████████████| 143kB 80.8MB/s 
Collecting matplotlib (from duplex_tools)
  Downloading https://files.pythonhosted.org/packages/09/03/b7b30fa81cb687d1178e085d0f01111ceaea3bf81f9330c937fb6f6c8ca0/matplotlib-3.3.4-cp36-cp36m-manylinux1_x86_64.whl (11.5MB)
    100% |████████████████████████████████| 11.5MB 4.2MB/s 
Collecting more-itertools (from duplex_tools)
  Downloading https://files.pythonhosted.org/packages/0b/ff/1ad78678bee731ae5414ea5e97396b3f91de32186028daa614d322ac5a8b/more_itertools-8.14.0-py3-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 57.3MB/s 
Collecting natsort (from duplex_tools)
  Downloading https://files.pythonhosted.org/packages/3e/58/61c4b4fd9e597affdcd3347d5991fa5be404af26f19932d3116b67e133da/natsort-8.2.0-py3-none-any.whl
Collecting numpy (from duplex_tools)
  Downloading https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl (13.4MB)
    100% |████████████████████████████████| 13.4MB 3.8MB/s 
Collecting pandas (from duplex_tools)
  Downloading https://files.pythonhosted.org/packages/c3/e2/00cacecafbab071c787019f00ad84ca3185952f6bb9bca9550ed83870d4d/pandas-1.1.5-cp36-cp36m-manylinux1_x86_64.whl (9.5MB)
    100% |████████████████████████████████| 9.5MB 8.5MB/s 
Collecting parasail (from duplex_tools)
  Downloading https://files.pythonhosted.org/packages/6d/fd/4696ce6a2e6ed2029dc4e1964f8cd68ffd693ed7a4f9aaf6c1990f355f0b/parasail-1.3.3.tar.gz (82kB)
    100% |████████████████████████████████| 92kB 61.5MB/s 
Collecting pod5 (from duplex_tools)
  Could not find a version that satisfies the requirement pod5 (from duplex_tools) (from versions: )
No matching distribution found for pod5 (from duplex_tools)
You are using pip version 18.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(duplex) (base) sheucke@PTH2D537:~/nanopore/tests$

**Comment by sheucke** [comment]
i could solve it, it looks like the python version of the environments was not high enough with 3.6, now with 3.9 its works.
