### ISSUE TITLE
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by defendant602** [nanoporetech/duplex-tools#7]
when I run the pairs_from_summary program, I got the error like this

`[10:55:41 - FindPairs] Duplex tools version: 0.2.7
Traceback (most recent call last):
  File "/export/pipeline/RNASeq/Software/Duplex_tools/bin/duplex_tools", line 11, in <module>
    load_entry_point('duplex-tools==0.2.7', 'console_scripts', 'duplex_tools')()
  File "/export/pipeline/RNASeq/Software/Duplex_tools/lib/python3.6/site-packages/duplex_tools/__init__.py", line 39, in main
    args.func(args)
  File "/export/pipeline/RNASeq/Software/Duplex_tools/lib/python3.6/site-packages/duplex_tools/pairs_from_summary.py", line 345, in main
    max_abs_seqlen_diff=args.max_abs_seqlen_diff)
  File "/export/pipeline/RNASeq/Software/Duplex_tools/lib/python3.6/site-packages/duplex_tools/pairs_from_summary.py", line 35, in find_pairs
    outdir, prefix, prepend_seqsummary_stem, sequencing_summary_path)
  File "/export/pipeline/RNASeq/Software/Duplex_tools/lib/python3.6/site-packages/duplex_tools/pairs_from_summary.py", line 101, in prepare_output_paths
    outdir.mkdir(parents=True, exist_ok=True)
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'`

That's my command line:

`duplex_tools pairs_from_summary sequencing_summary.txt ./output`

Could you please help me check this out? Thansk !

**Comment by Rasinj** [comment]
Hi!

That's mysterious, Pathlib should have the exist_ok argument added from 3.5, and it looks like you're using 3.6.

Can you run this line below (swapping out python for the interpreter you're using if necessary)?

```
python -c "from pathlib import Path; Path('./output').mkdir(exist_ok=True)"
```

Let me know if that's giving the same error. You may want to try with python3.8 instead if it does.

**Comment by defendant602** [comment]
Thanks for your reply. I swapped out python for the python I used for duplex_tools and run the above command. It gave the same error. 

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'`

I will try with another python version. Thanks.

**Comment by defendant602** [comment]
Hi , @Rasinj 
   I reinstalled duplex_tools using python 3.8, run the same command : duplex_tools pairs_from_summary sequencing_summary.txt ./output   , but the problem still exists.


```
[19:03:13 - FindPairs] Duplex tools version: 0.2.7
Traceback (most recent call last):
  File "/export/pipeline/RNASeq/Software/Duplex_tools/bin/duplex_tools", line 8, in <module>
    sys.exit(main())
  File "/export/pipeline/RNASeq/Software/Duplex_tools/lib/python3.8/site-packages/duplex_tools/__init__.py", line 39, in main
    args.func(args)
  File "/export/pipeline/RNASeq/Software/Duplex_tools/lib/python3.8/site-packages/duplex_tools/pairs_from_summary.py", line 336, in main
    find_pairs(
  File "/export/pipeline/RNASeq/Software/Duplex_tools/lib/python3.8/site-packages/duplex_tools/pairs_from_summary.py", line 34, in find_pairs
    outdir, output_pairs, output_intermediate = prepare_output_paths(
  File "/export/pipeline/RNASeq/Software/Duplex_tools/lib/python3.8/site-packages/duplex_tools/pairs_from_summary.py", line 101, in prepare_output_paths
    outdir.mkdir(parents=True, exist_ok=True)
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'
```

**Comment by defendant602** [comment]
I checked my pathlib package version, it's 1.0.1.  Is this version too old for duplex_tools?

but pip automatically installed pathlib 1.0.1 when I install duplex_tools. 

Maybe the dependencies to install duplex_tools should be modified a little?

**Comment by Rasinj** [comment]
Hi @defendant602, ah I think that must be it. Thanks for noticing. In fact, I believe it should be included by default, so perhaps the most sensible thing is to remove it as an explicit dependency
